version: "{build}"

image: Visual Studio 2015

branches:
  only:
    - release

skip_non_tags: true

environment:
  pcre2: "10.21"
  ssl: "2.5.0"
  matrix:
  - llvm: "4.0.0"
  - llvm: "3.9.1"
  - llvm: "3.8.1"
  - llvm: "3.7.1"

configuration:
  - Debug
  - Release

build_script:
  - ps: |
      $config = $env:configuration
      $pcre2 = $env:pcre2
      $ssl = $env:ssl
      $llvm = $env:llvm
      $tag = $env:APPVEYOR_REPO_TAG_NAME

      $workingDir = Convert-Path "."
      & "$workingDir\build.ps1" -config $config -pcre2 $pcre2 -ssl $ssl -llvm $llvm -workingDir $workingDir -tag $tag

artifacts:
  - path: 'PonyWinLibs*.zip'

deploy:
  - provider: GitHub
    description: Windows libraries for building the Pony compiler and standard library
    auth_token:
      secure: VWcomibzQA0AdttM8KDjvBTfHIoxXkLCzuoWzlV3om8bDO4CpUfu88Q7DltN710l
    artifact: /PonyWinLibs.*\.zip/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
